<div class="center well white">
	<div class="center">
		<h1>Välkommen till Kviddevitter!</h1>
		<br />
		<p>
			För att börja kvittra så måste du antingen logga in eller registrera dig:
		</p>
		<br />
		<p>
			<strong class="leftside"><a class="well" href="/authentication/login">Logga in</a></strong>
			<strong class="rightside"><a class="well" href="/authentication/register">Registrera</a></strong>
		</p>
	</div>
	<br /><br />
</div>