<ul class="nav nav-pills center">
	<li><a href="/tweets/mytweets">Mina tweets</a></li>
	<li class="active"><a href="/tweets/myflow">Mitt flöde</a></li>
	<li><a href="/tweets/myprofile">Min profil</a></li>
</ul>

<br /><br />

<div id="tweetspace">

<div id="innertweets">
	<?php
	$this->jQuery()->addOnLoad("");


	if($this->tweetflow != null)
	{
		$list = new Application_Model_ListTweets();
		$tweetsList = $this->tweetflow;
		$allUsers = $this->allUsers;
		
		$tweetsShowing = 10;
		
		$i = 0;
		for($i = 0; $i < $tweetsShowing && $i < count($tweetsList); $i++)
		{
			$tweet = $tweetsList[$i];
			$userinfo = $this->userinfo[$tweet->userid];
			
			echo '<div class="reply">';
			
			//Ta fram tweeten som det här är svar på om det finns någon
			if($tweet->replyto != null)
			{
				$tweetAbove = $list->getTweetById($tweet->replyto);
				$user = $allUsers[$tweetAbove->userid];
				
				echo '<div class="well tweetsabove">';
				tweetContent($user, $tweetAbove, $list);
				echo '<div class="form2"></div>';
				echo '</div>';
				
			}
			
			//Huvud-Tweet
			echo '<div class="well tweetbox">';
			tweetContent($userinfo, $tweet, $list);
			echo '<div class="form2"></div>';
			echo '</div>';
			
			
			//Svar
			$tweetsBelow = $list->getReplies($tweet->tweetid);
			if(count($tweetsBelow) > 0)
			{
				foreach($tweetsBelow as $reply)
				{
					$user = $allUsers[$reply->userid];
					
					echo '<div class="well tweetsbelow">';
					tweetContent($user, $reply, $list);
					echo '<div class="form2"></div>';
					echo '</div>';
				}
			}
			
			echo '</div>';
		}
		$tweetsShowing = $i;
		
		echo '<input id="moretweets" class="btn" type="button" value="Fler tweets" />';
	}
	?>
	</div>
	<div id="loading"></div>


	<?php
	function tweetContent($user, $tweet, $tweetsList)
	{
		echo '<div class="clickableTweet">';
		echo '<img class="avatar" src="/Image/thumbnail?image='.substr($user->userimage, 1, strlen($user->userimage)).'" />';
		echo '<strong>'.$user->firstname.' '.$user->lastname.'</strong> @'.$user->username.'<br />'.$tweet->message.'<br /><br /><br />';
		echo '<div id="id" class="invisible">'.$tweet->tweetid.'</div>';
		$tweetsList->timeSince($tweet->timestamp);
		echo '</div>';
		echo '<div class="replylink"></div>';
	}
	?>

</div>