
<ul class="nav nav-pills center">
	<li class="active"><a href="/tweets/mytweets">Mina tweets</a></li>
	<li><a href="/tweets/myflow">Mitt flöde</a></li>
	<li><a href="/tweets/myprofile">Min profil</a></li>
</ul>

<br /><br />



<div id="tweetspace">
	<div class="well">
		<?php
			$userObject = Zend_Auth::getInstance()->getIdentity();
			echo '<label id="userid" class="invisible">'.$userObject->userid.'</label>';
			echo '<img class="rightside" src="/Image/thumbnail?image='.substr($userObject->userimage, 1, strlen($userObject->userimage)).'" />'; 
		?>
		
		<h2><?php echo $this->userinfo->firstname.' '.$this->userinfo->lastname ?></h2>
		<div class="username"><?php echo '@'.$this->userinfo->username ?></div>
		<br />
		<p class="description"><?php echo $this->userinfo->description ?></p>
		<?php echo $this->userinfo->location.' <br /><a href="http://'.$this->userinfo->website.'">'.$this->userinfo->website.'</a>' ?>
	</div>

	<form id="form" action="/tweets/writetweets" method="POST">
		<textarea id="tweetarea" name="message"></textarea>
		<br />
		<input id="button" type="submit" class="btn btn-primary" value="Posta" />
		<input id="id" class="invisible" type="text" value="" name="id" />
		<div id="feedback"></div>
	</form>
	
	

	<div id="innertweets">
		<?php
		$this->jQuery()->addOnLoad("");
		
		writeTweets($this->tweetsList, $this->allUsers);

		?>
	</div>
	<div id="loading"></div>
</div>


<?php 
function writeTweets($tweetsList, $allUsers)
{
	$list = new Application_Model_ListTweets();

	$tweetsShowing = 10;
	
	$userObject = Zend_Auth::getInstance()->getIdentity();
	
	$i = 0;
	for($i = 0; $i < $tweetsShowing && $i < count($tweetsList); $i++)
	{
		$tweet = $tweetsList[$i];
		
		echo '<div class="reply">';
		
		//Ta fram tweeten som det här är svar på om det finns någon
		if($tweet->replyto != null)
		{
			$tweetAbove = $list->getTweetById($tweet->replyto);
			$user = $allUsers[$tweetAbove->userid];
			
			echo '<div class="well tweetsabove">';
			tweetContent($user, $tweetAbove, $list);
			echo '<div class="form2"></div>';
			echo '</div>';
			
		}
		
		//Huvud-Tweet
		echo '<div class="well tweetbox">';
		tweetContent($userObject, $tweet, $list);
		echo '<div class="form2"></div>';
		echo '</div>';
		
		
		
		//Svar
		$tweetsBelow = $list->getReplies($tweet->tweetid);
		if(count($tweetsBelow) > 0)
		{
			foreach($tweetsBelow as $reply)
			{
				$user = $allUsers[$reply->userid];
				
				echo '<div class="well tweetsbelow">';
				tweetContent($user, $reply, $list);
				echo '<div class="form2"></div>';
				echo '</div>';
				
			}
		}
		
		echo '</div>';
	}
	$tweetsShowing = $i;
	
	echo '<input id="moretweets" class="btn" type="button" value="Fler tweets" />';
}


function tweetContent($user, $tweet, $tweetsList)
{
	echo '<div class="clickableTweet">';
	echo '<img class="avatar" src="/Image/thumbnail?image='.substr($user->userimage, 1, strlen($user->userimage)).'" />';
	echo '<strong>'.$user->firstname.' '.$user->lastname.'</strong> @'.$user->username.'<br />';
	if($tweet->replyto != null)
	{
		$username = $tweetsList->getUser($tweetsList->getTweetById($tweet->replyto)->userid)->username;
		echo '<a href="/'.$username.'">@'.$username.'</a> ';
	}
	echo $tweet->message.'<br /><br /><br />';
	echo '<div id="id" class="invisible">'.$tweet->tweetid.'</div>';
	$tweetsList->timeSince($tweet->timestamp);
	echo '</div>';
	echo '<div class="replylink"></div>';
}
?>