<?php

//Inkludera jquery-grejerna här eftersom layout är disabled
echo $this->jQuery();
echo '<script type="text/javascript" src="/js/tweets.js"></script>';

$tweetsShowing = 10;
$flow = null;

if($_SERVER["REQUEST_METHOD"] == "POST")
{
	$tweetsList = new Application_Model_ListTweets();
	$userid = Zend_Auth::getInstance()->getIdentity()->userid;
	$userinfo = null;
	
	if(isset($_POST['message']) && isset($_POST['id']))
	{
		$message = $_POST['message'];
		
		if($_POST['id'] != "")
			$replyid = $_POST['id'];
		else
			$replyid = null;
		
		$tweetsList->addTweet($message, $replyid);
	}
	
	//Om vi skickar med hur många som ska visas
	if(isset($_POST['tweets']))
	{
		$tweetsShowing = $_POST['tweets'];
	}
	
	
	//Om det är myflow som anropar writetweets
	if(isset($_POST['flow']))
	{
		$userinfo = $this->userinfo;
		$flow = $this->tweetflow;
	}
	
	if(isset($_POST['userid']))
	{
		$userid = $_POST['userid'];
	}
	
	
	
	$tweetsList = new Application_Model_ListTweets();
	
	$tweetsList = $tweetsList->listTweets($userid, $tweetsShowing);
	
	$latestTweet = $tweetsList[0][0];
	writeTweets($tweetsList[0], $this->allUsers, $tweetsShowing, $flow, $userinfo);
}


function writeTweets($tweets, $allUsers, $tweetsShowing, $flow, $info)
{
	$list = new Application_Model_ListTweets();
	$tweetsList = $tweets;
	$userinfo = Zend_Auth::getInstance()->getIdentity();
	
	//Kolla om det är ett flöde som ska ritas ut
	if($flow != null)
	{
		$tweetsList = $flow;
	}
	
	$i = 0;
	for($i = 0; $i < $tweetsShowing && $i < count($tweetsList); $i++)
	{
		//echo $i.'<br />';
		
		$tweet = $tweetsList[$i];
		
		if($info != null)
			$userinfo = $info[$tweet->userid];
		$userinfo = $allUsers[$tweet->userid];
		echo '<div class="reply">';
		
		//Ta fram tweeten som det här är svar på om det finns någon
		if($tweet->replyto != null)
		{
			$tweetAbove = $list->getTweetById($tweet->replyto);
			$user = $allUsers[$tweetAbove->userid];
			
			echo '<div class="well tweetsabove">';
			tweetContent($user, $tweetAbove, $list);
			echo '<div class="form2"></div>';
			echo '</div>';
		}
		
		//Huvud-Tweet
		echo '<div class="well tweetbox">';
		tweetContent($userinfo, $tweet, $list);
		echo '<div class="form2"></div>';
		echo '</div>';
		
		
		//Svar
		$tweetsBelow = $list->getReplies($tweet->tweetid);
		if(count($tweetsBelow) > 0)
		{
			foreach($tweetsBelow as $reply)
			{
				$user = $allUsers[$reply->userid];
				
				echo '<div class="well tweetsbelow">';
				tweetContent($user, $reply, $list);
				echo '<div class="form2"></div>';
				echo '</div>';
			}
		}
		
		echo '</div>';
	}
	$tweetsShowing = $i;
	
	echo '<input id="moretweets" class="btn" type="button" value="Fler tweets" />';
}


function tweetContent($user, $tweet, $tweetsList)
{
	echo '<div class="clickableTweet">';
	echo '<img class="avatar" src="/Image/thumbnail?image='.substr($user->userimage, 1, strlen($user->userimage)).'" />';
	echo '<strong>'.$user->firstname.' '.$user->lastname.'</strong> @'.$user->username.'<br />'.$tweet->message.'<br /><br /><br />';
	echo '<div id="id" class="invisible">'.$tweet->tweetid.'</div>';
	$tweetsList->timeSince($tweet->timestamp);
	echo '</div>';
	echo '<div class="replylink"></div>';
}

?>