<?php

header('Content-type: image/jpg');

if(isset($_GET['image']))
{
	$image = $_GET['image'];
	
	$image_size = getimagesize($image);
	
	$image_width = $image_size[0];
	$image_height = $image_size[1];
	
	$new_size = ($image_width + $image_height) / ($image_width * ($image_height / 45));
	$new_width = $image_width * $new_size;
	$new_height = $image_height * $new_size;
	
	//skapa en tom ny bild med rätt storlek
	$new_image = imagecreatetruecolor($new_width, $new_height);
	
	//skapa en variabel som är den gamla bilden
	if(substr($image, -4, 4) == '.png')
	{
		$old_image = imagecreatefrompng($image);
	}
	else
	{
		$old_image = imagecreatefromjpeg($image);
	}
	
	//Stoppa in en nedskalad version av den gamla bilden i den nya bilden
	imagecopyresized($new_image, $old_image, 0, 0, 0, 0, $new_width, $new_height, $image_width, $image_height);
	imagepng($new_image);
}
?>